### ISSUE TITLE
Esp32, Arduino how do I know the correct angle of the device?

### ISSUE THREAD

**Issue by bbhxwl** [bolderflight/invensense-imu#113]
Esp32, Arduino how do I know the correct angle of the device?

**Comment by flybrianfly** [comment]
This is the axis orientation:
https://github.com/bolderflight/mpu9250#sensor-orientation

The sensor gives measurements of linear acceleration and rotational rates. Rotation angles are not measured directly and can be estimated using different approaches and filters, which are not included with this library since there are many to choose from and they are application specific.
