### ISSUE TITLE
FIFO Functionality planned?

### ISSUE THREAD

**Issue by JRoseCPMax** [bolderflight/invensense-imu#91]
In version 1.0 the library included the usage of the FIFO Library. Is there a particular reason why you stopped supporting it? Do you plan to introduce it again in the future?

**Comment by flybrianfly** [comment]
We stopped supporting it for a few reasons:
1. It expands the footprint of the library's API and was challenging to document in a way that was approachable to users. The larger API requires more effort to maintain.
2. With newer boards, some timing issues were showing up using the FIFO.
3. Internally, we don't use the FIFO, which made supporting it more challenging.

I don't plan on introducing FIFO support in the future. We purposefully aligned the API with the most commonly used features from our user base and those that we use often to make it easy to maintain going forward. 

The older versions of the library worked well, so I wouldn't feel a pressing need to update to the newest, otherwise, the library can be forked and the FIFO pulled in.
